import os
Import('env')
env = env.Clone()

includePath = []
includePath.append('.')
includePath.append('../../../c')
includePath.append('#common/c_cpp/src/c')
includePath.append('$prefix/include')

libPath = []
libPath.append('$prefix/lib')

env.Append( LIBPATH = libPath )
env.Append( CPPPATH = [ includePath ] )
env.Append( LIBS = [ 'mama','pthread','m','wombatcommon','dl' ] )

capturereplayc = env.Program('capturereplayc','capturereplayc.c')
capturec = env.Program('capturec','capturec.c')
captureconvert = env.Program('captureconvert','captureconvert.c')

Alias('install',env.Install('$bindir',capturereplayc))
Alias('install',env.Install('$bindir',capturec))
Alias('install',env.Install('$bindir',captureconvert))
