import os
Import('env')
env = env.Clone()

includePath = []
includePath.append('.')
includePath.append('..')
includePath.append('../..')
includePath.append('../../../c')
includePath.append('../../../cpp')
includePath.append('#common/c_cpp/src/c')
includePath.append('#common/c_cpp/src/cpp')
includePath.append('$prefix/include')

libPath = []
libPath.append('$prefix/lib')

env.Append( LIBPATH = libPath )
env.Append( CPPPATH = [ includePath ] )
env.Append( LIBS = [ 'mamacpp','mama','dl','pthread' ] )

mamachurn = env.Program('mamachurncpp','mamachurncpp.cpp')

Alias('install',env.Install('$bindir',mamachurn))
