Import('env')
env = env.Clone()

env['with_libxml'] = False

# Check for the presence of various functions/headers and in the case
# of there existence set DEFINES to be passed to the compiler. Mainly
# These are used in libevent to modify the includes
conf = Configure( env ,config_h = './config.h',log_file='./config.log')

if not env.GetOption('clean'):
    if conf.CheckLib('libxml2'):
        conf.env.Append(
            CPPDEFINES = 'WITH_LIBXML',
            CPPPATH = ['/usr/include/libxml2/'],
            with_libxml = True
         )

env = conf.Finish()

env.SConscript('src/c/SConscript','env')
env.SConscript('src/cpp/SConscript','env')

if env.get('with_enterprise',None) == True:
   env.SConscript('src/enterprise/SConscript','env')

if env['with_unittest'] == True:
    env.SConscript('src/gunittest/SConscript','env')
