#!/usr/bin/python
# -*- coding: utf-8 -*-
import os
Import('env')
env = env.Clone()

includePath = []
includePath.append('.')

env.Append(CPPPATH=includePath)

env.Object('MainUnitTest', 'MainUnitTest.cpp')
env.Object('MamdaUnitTestUtils', 'MamdaUnitTestUtils.cpp')
