#!/usr/bin/python
# -*- coding: utf-8 -*-
import os
Import('*')
env = env.Clone()

target = 'libmamaavismsgimpl'

includePath = []
includePath.append('.')
includePath.append('../..')
includePath.append('$avis_home/include')
includePath.append('#common/c_cpp/src/c')

libPath = []
libPath.append('$avis_home/lib')

env['CCFLAGS'] = [x for x in env['CCFLAGS'] if x != '-pedantic-errors']

env.Append(LIBS=['mama', 'avis', 'm'], LIBPATH=libPath,
           CPPPATH=[includePath])

sources = Glob('*.c')

lib = []
lib.append(env.SharedLibrary(target, sources))
lib.append(env.StaticLibrary(target, sources))

Alias('install', env.Install('$libdir', lib))
