#!/usr/bin/python
# -*- coding: utf-8 -*-
import subprocess
import os
Import('*')
env = env.Clone()

target = 'UnitTestCommonC'

incpath = []
incpath.append('.')
incpath.append('$incdir')
incpath.append('#common/c_cpp/src/c')
incpath.append('#common/c_cpp/src/c/' + env['host']['os'].lower())
incpath.append('#common/c_cpp/src/gunittest')
incpath.append('#mama/c_cpp/src/c')

libpath = []
libpath.append('$libdir')
libs = []
if env['PLATFORM'] == "win32":
    libs.append('libmamac%s' % ( env['suffix'] ))
    libs.append('libwombatcommon%s' % ( env['suffix'] ))
else:
    libs = ['dl', 'wombatcommon', 'mama', 'pthread']
    env['CCFLAGS'] = [x for x in env['CCFLAGS'] if x != '-pedantic-errors']

env.Append(LIBPATH=libpath, LIBS=libs, CPPPATH=incpath)

sources = Split("""
port.cpp
queuetest.cpp
timertest.cpp
utiltest.cpp
strutilstest.cpp
""")

MainUnitTest = env.Object( '../MainUnitTestC.cpp' ) 
sources.append( MainUnitTest )

bin = env.Program(target, sources)

Alias('install', env.Install('$bindir', bin))

env.PrependENVPath('LD_LIBRARY_PATH', Dir('%s/lib' % env['prefix'
                   ]).abspath)

bins = []


Alias( 'install',env.Install('$bindir',bins) )

def runUnitTest(env, target, program):
    env = dict(os.environ)
    env['LD_LIBRARY_PATH'] = Dir('$libdir').abspath
    args = ['--gtest_output=%s' % target]
    p = subprocess.Popen(
        args,
        shell=True,
        stdin=subprocess.PIPE,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        env=env,
        )
    p.communicate()[0]
    print 'Finished'


if 'test' in BUILD_TARGETS:
    test_alias = Alias('test', env.Command('%s.xml' % bin[0].name, bin,
                       '$SOURCE --gtest_output=xml:$TARGET'))
    AlwaysBuild(test_alias)
