#!/usr/bin/python
# -*- coding: utf-8 -*-
import os
Import('env')
env = env.Clone()

examples = Glob('*.cpp')

env.Append(LIBS=['mamdanews'])

bins = ['newsticker']

binary = []

# parsecmdObj = env.Object( 'parsecmd', 'parsecmd.cpp' )
# dictrequesterObj = env.Object( 'dictrequester', 'dictrequester.cpp' )

for b in bins:
    binary.append(env.Program(b, ['%s.cpp' % b, '../parsecmd.o',
                  '../dictrequester.o']))

Alias('install', env.Install('$bindir', binary))
Alias('install', env.Install('$prefix/examples/mamda/cpp/news',
      examples))
