import os
Import('env')
env = env.Clone()

includePath = []
includePath.append('.')
includePath.append('../../../c')
includePath.append('#common/c_cpp/src/c')
includePath.append('#common/c_cpp/src/c/' + env['host']['os'].lower())
includePath.append('$prefix/include')

libPath = []
libPath.append('$prefix/lib')

sources = Glob('*.c')

env.Append( LIBPATH = libPath )
env.Append( CPPPATH = [ includePath ] )
env.Append( LIBS = [ 'mama','pthread','m','wombatcommon','dl' ] )

mamachurn = env.Program('mamachurnc','mamachurnc.c')

Alias('install',env.Install('$bindir',mamachurn))
