#!/usr/bin/python
# -*- coding: utf-8 -*-
Import('env')
import os
env = env.Clone()

incpath = []
incpath.append('$gtest_home/include')

libpath = []
libs = []

libpath.append('$gtest_home/lib')
libs = ['gtest', 'gtest_main']

env.Append(LIBPATH=libpath, CPPPATH=incpath, LIBS=libs)

env.SConscript('c/SConscript', 'env')
