import os
Import('env')
env = env.Clone()

includePath = []
includePath.append('.')
includePath.append('../../../c')
includePath.append('#common/c_cpp/src/c')
includePath.append('$prefix/include')

libPath = []
libPath.append('$prefix/lib')

sources = Glob('*.c')

env.Append( LIBPATH = libPath )
env.Append( CPPPATH = [ includePath ] )
env.Append( LIBS = [ 'mama','pthread','m','wombatcommon','dl','rt' ] )

mamaproducer = env.Program('mamaproducerc','mamaproducerc.c')
mamaconsumer = env.Program('mamaconsumerc','mamaconsumerc.c')
#mamaconsumerv2 = env.Program('mamaconsumerc_v2','mamaconsumerc_v2.c')
mamapingpong = env.Program('mamapingpongc','mamapingpongc.c')

Alias('install',env.Install('$prefix/bin',mamaproducer))
Alias('install',env.Install('$prefix/bin',mamaconsumer))
#Alias('install',env.Install('$prefix/bin',mamaconsumerv2))
Alias('install',env.Install('$prefix/bin',mamapingpong))
