#!/usr/bin/python
# -*- coding: utf-8 -*-
import os
Import('*')
env = env.Clone()

InstMamdaBookInclude = \
    Split("""
	mamda/MamdaBookAtomicGap.h
	mamda/MamdaBookAtomicLevel.h
	mamda/MamdaBookAtomicLevelEntry.h
	mamda/MamdaBookAtomicLevelHandler.h
	mamda/MamdaBookAtomicLevelEntryHandler.h
	mamda/MamdaBookAtomicListener.h
	mamda/MamdaBookAtomicBookHandler.h
	mamda/MamdaOrderBook.h
	mamda/MamdaOrderBookBasicDelta.h
	mamda/MamdaOrderBookBasicDeltaList.h
	mamda/MamdaOrderBookComplexDelta.h
	mamda/MamdaOrderBookChecker.h
	mamda/MamdaOrderBookCheckerHandler.h
	mamda/MamdaOrderBookCheckType.h
	mamda/MamdaOrderBookClear.h
	mamda/MamdaOrderBookConcreteComplexDelta.h
	mamda/MamdaOrderBookConcreteSimpleDelta.h
	mamda/MamdaOrderBookDelta.h
	mamda/MamdaOrderBookEntry.h
	mamda/MamdaOrderBookEntryFilter.h
	mamda/MamdaOrderBookEntryManager.h
	mamda/MamdaOrderBookExceptions.h
	mamda/MamdaOrderBookFields.h
	mamda/MamdaOrderBookGap.h
	mamda/MamdaOrderBookHandler.h
	mamda/MamdaOrderBookListener.h
	mamda/MamdaOrderBookPriceLevel.h
	mamda/MamdaOrderBookRecap.h
	mamda/MamdaOrderBookSimpleDelta.h
	mamda/MamdaOrderBookTypes.h
	mamda/MamdaQuoteToBookListener.h
""")

includePath = []
includePath.append('.')
includePath.append('..')
includePath.append('#mama/c_cpp/src/c')
includePath.append('#mama/c_cpp/src/cpp')
includePath.append('#mama/c_cpp/src/cpp/mama')
includePath.append('#common/c_cpp/src/c')
includePath.append('$prefix/include')

libPath = []
libPath.append('$prefix/lib')

sources = \
    Split("""
   MamdaBookAtomicListener.cpp
   MamdaOrderBook.cpp
   MamdaOrderBookBasicDelta.cpp
   MamdaOrderBookBasicDeltaList.cpp
   MamdaOrderBookChecker.cpp
   MamdaOrderBookCheckType.cpp
   MamdaOrderBookConcreteComplexDelta.cpp
   MamdaOrderBookConcreteSimpleDelta.cpp
   MamdaOrderBookSimpleDelta.cpp
   MamdaOrderBookEntry.cpp
   MamdaOrderBookEntryManager.cpp
   MamdaOrderBookFields.cpp
   MamdaOrderBookListener.cpp
   MamdaOrderBookPriceLevel.cpp
   MamdaOrderBookWriter.cpp
   MamdaQuoteToBookListener.cpp
""")

env.Append(LIBS=['mamda','mamacpp'],CPPFLAGS=['-Wno-non-virtual-dtor'], CPPPATH=includePath,
           LIBPATH=libPath)

target = 'libmamdabook'
lmamdabookso = env.SharedLibrary(target, sources)
lmamdabook = env.StaticLibrary(target, [ sources, StaticLibs['libwombatcommon'] ])

Alias('install', env.Install('$libdir', lmamdabook))
Alias('install', env.Install('$libdir', lmamdabookso))

Alias('install', env.Install('$prefix/include/mamda',
      InstMamdaBookInclude))
