/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package quickstart;

import com.wombat.mama.Mama;
import com.wombat.mama.MamaBridge;

public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        MamaBridge bridge = Mama.loadBridge ("qpid");
        System.out.println(Mama.getVersion(bridge));
    }
}
