#!/usr/bin/python
# -*- coding: utf-8 -*-
import os
Import('*')
env = env.Clone()

target = 'libmamaentnoop'

includePath = []
includePath.append('#mama/c_cpp/src/c')
includePath.append('.')

sources = Glob('*.c')

if env['PLATFORM'] == "win32":
    libs = []
    libs.append('libwombatcommon%s.lib' % ( env['suffix'] ))
    libs.append('libmamac%s.lib' % ( env['suffix'] ))
    env.Append(LIBS=libs, CPPPATH=[includePath])
    env.InstallLibrary(sources, target)
else:
    env.Append(LIBS=['mama', ], CPPPATH=[includePath])
    env['CCFLAGS'] = [x for x in env['CCFLAGS'] if x != '-pedantic-errors']
    env.Append(CFLAGS=['-Werror'])
    Alias('install', env.Install('$libdir', lib))