import os
Import('env')
env = env.Clone()

includePath = []
includePath.append('.')
includePath.append('..')
includePath.append('../..')
includePath.append('../../../c')
includePath.append('../../../cpp')
includePath.append('#common/c_cpp/src/c')
includePath.append('#common/c_cpp/src/c/' + env['host']['os'].lower())
includePath.append('#common/c_cpp/src/cpp')
includePath.append('$prefix/include')

libPath = []
libPath.append('$prefix/lib')

env.Append( LIBPATH = libPath )
env.Append( CPPPATH = [ includePath ] )
env.Append( LIBS = [ 'mamacpp','mama','dl','pthread','wombatcommon' ] )

replycpp = env.Program('mamapingpong_replycpp','mamapingpong_replycpp.cpp')
requestercpp = env.Program('mamapingpong_requestercpp','mamapingpong_requestercpp.cpp')

Alias('install',env.Install('$prefix/bin',replycpp))
Alias('install',env.Install('$prefix/bin',requestercpp))
