set(SYSTEM_SOURCES
	linux/environment.c
        linux/network.c
        linux/platform.c
        linux/machine.c
        darwin/wSemaphore.c
        darwin/port.c
        darwin/clock.c
        darwin/wUuid.c
)
