#!/usr/bin/python
# -*- coding: utf-8 -*-
import os
Import('*')
env = env.Clone()

target = 'libmamaoeaimpl'

includePath = []
includePath.append(os.path.join(env['oea_home'],'include/oea'))
includePath.append('#mama/c_cpp/src/c')
includePath.append('.')

libPath = []
libPath.append(os.path.join(env['oea_home'],'lib'))

env['CCFLAGS'] = [x for x in env['CCFLAGS'] if x != '-pedantic-errors']

env.Append(LIBS=['mama', 'oeac', ], 
           LIBPATH=libPath,
           CPPPATH=[includePath])

sources = Glob('*.c')

lib = []
lib.append(env.SharedLibrary(target, sources))
lib.append(env.StaticLibrary(target, sources))

Alias('install', env.Install('$libdir', lib))
