name: CVE Scanning for Docker

on:
  push:
    paths:
      - 'docker/Dockerfile'
      - '.github/workflows/cve-scanning-docker.yml'

jobs:
  scan-docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: docker-practice/actions-setup-docker@1.0.11
      - name: Build
        run: docker build -f Dockerfile -t user/app:latest .
        working-directory: docker
      - name: Scan for vulnerabilities
        uses: crazy-max/ghaction-container-scan@v2
        with:
          image: user/app:latest