name: CVE Scanning for Gradle

on:
  push:
    paths:
      - '**/build.gradle'
      - 'allow-list.xml'
      - '.github/workflows/cve-scanning-gradle.yml'

jobs:
  scan:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        folder-name: ["mama/jni", "mamda/java"]
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Build with Gradle
        run: ./gradlew build
        working-directory: ${{ matrix.folder-name }}
      - name: CVEs
        run: ./gradlew dependencyCheckAnalyze
        working-directory: ${{ matrix.folder-name }}